<a href="https://colab.research.google.com/github/baerashid/755/blob/tf-2.x/hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#The default is TF 1.0, so forcing to use 2.0
!pip uninstall tensorflow

In [0]:
!pip install tensorflow==2.1.0

In [0]:
#Now we have to restart Runtime
#Click above

In [1]:
import numpy as np
import tensorflow as tf
print(tf.__version__)

2.1.0


Problem 1

In [0]:
P = np.array([[0.5,0,0.5,],
             [0,0.75,0.25],
             [0.5,0.5,0]])

In [3]:
P

array([[0.5 , 0.  , 0.5 ],
       [0.  , 0.75, 0.25],
       [0.5 , 0.5 , 0.  ]])

In [0]:
pi0 = np.array([1,0,0], dtype=float)

In [5]:
pi0

array([1., 0., 0.])

In [6]:
#P to the 3rd power
P3 = np.dot(np.dot(P,P),P)
P3

array([[0.375   , 0.3125  , 0.3125  ],
       [0.15625 , 0.609375, 0.234375],
       [0.3125  , 0.46875 , 0.21875 ]])

In [7]:
np.sum(P3,axis=1)

array([1., 1., 1.])

In [0]:
pi3 = np.dot(pi0,P3)

In [9]:
pi3

array([0.375 , 0.3125, 0.3125])

In [10]:
np.sum(pi3)

1.0

In [11]:
pi1 = np.dot(pi0,P)
pi1

array([0.5, 0. , 0.5])

In [12]:
pi2 = np.dot(pi1,P)
pi2

array([0.5 , 0.25, 0.25])

In [13]:
pi33 = np.dot(pi2,P)
pi33

array([0.375 , 0.3125, 0.3125])

In [15]:
tfP = tf.constant([[0.5,0,0.5,],
                   [0,0.75,0.25],
                   [0.5,0.5,0]])
tf.print(tfP)
#with tf.Session() as sess:  print(tfP.eval()) 

[[0.5 0 0.5]
 [0 0.75 0.25]
 [0.5 0.5 0]]


In [16]:
tfpi0 = tf.constant([1,0,0], dtype=float)
tf.print(tfpi0)

[1 0 0]


In [17]:
tfpi1 = tf.linalg.matvec(tfP,tfpi0)
tf.print(tfpi1)

[0.5 0 0.5]


In [18]:
tfP3 = tf.matmul(tfP,tf.matmul(tfP,tfP))
tf.print(tfP3)

[[0.375 0.3125 0.3125]
 [0.15625 0.609375 0.234375]
 [0.3125 0.46875 0.21875]]


In [19]:
P3

array([[0.375   , 0.3125  , 0.3125  ],
       [0.15625 , 0.609375, 0.234375],
       [0.3125  , 0.46875 , 0.21875 ]])

In [20]:
tfpi3 = tf.matmul(tf.expand_dims(tfpi0,0),tfP3)
tf.print(tfpi3)

[[0.375 0.3125 0.3125]]


In [21]:
pi3

array([0.375 , 0.3125, 0.3125])

In [0]:
tfpi0_0 = tf.constant([0.25,0.5,0.25])

In [23]:
tfpi1_1 = tf.matmul(tf.expand_dims(tfpi0_0,0),tfP)
tf.print(tfpi1_1)

[[0.25 0.5 0.25]]


Problem 2

In [0]:
T = tf.Variable(tf.zeros([7,7],dtype=float))

In [35]:
tf.print(T)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [38]:
T[0,1].assign(1)
T[1,2].assign(0.5)
T[1,6].assign(0.5)
T[2,2].assign(1)
T[3,5].assign(1)
T[4,3].assign(1./3)
T[4,5].assign(1./3)
T[4,6].assign(1./3)
T[5,3].assign(1)
T[5,0].assign(0.5)
T[5,3].assign(0.5)

<tf.Variable 'UnreadVariable' shape=(7, 7) dtype=float32, numpy=
array([[1.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.5       , 0.        , 0.        ,
        0.        , 0.5       ],
       [0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.        ],
       [0.        , 0.        , 0.        , 0.33333334, 0.        ,
        0.33333334, 0.33333334],
       [0.5       , 0.        , 0.        , 0.5       , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ]], dtype=float32)>

In [39]:
T

<tf.Variable 'Variable:0' shape=(7, 7) dtype=float32, numpy=
array([[1.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.5       , 0.        , 0.        ,
        0.        , 0.5       ],
       [0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.        ],
       [0.        , 0.        , 0.        , 0.33333334, 0.        ,
        0.33333334, 0.33333334],
       [0.5       , 0.        , 0.        , 0.5       , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ]], dtype=float32)>