<a href="https://colab.research.google.com/github/baerashid/755/blob/master/hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np


In [0]:
P = np.array([[0.5,0,0.5,],
             [0,0.75,0.25],
             [0.5,0.5,0]])

In [6]:
P

array([[0.5 , 0.  , 0.5 ],
       [0.  , 0.75, 0.25],
       [0.5 , 0.5 , 0.  ]])

In [0]:
pi0 = np.array([1,0,0], dtype=float)

In [8]:
pi0

array([1., 0., 0.])

In [0]:
#P to the 3rd power
P3 = np.dot(np.dot(P,P),P)

In [19]:
np.sum(P3,axis=1)

array([1., 1., 1.])

In [0]:
pi3 = np.dot(pi0,P3)

In [21]:
pi3

array([0.375 , 0.3125, 0.3125])

In [23]:
np.sum(pi3)

1.0

In [24]:
pi1 = np.dot(pi0,P)
pi1

array([0.5, 0. , 0.5])

In [25]:
pi2 = np.dot(pi1,P)
pi2

array([0.5 , 0.25, 0.25])

In [26]:
pi33 = np.dot(pi2,P)
pi33

array([0.375 , 0.3125, 0.3125])