<a href="https://colab.research.google.com/github/baerashid/755/blob/tf-2.x/hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#The default is TF 1.0, so forcing to use 2.0
!pip uninstall tensorflow

In [28]:
!pip install tensorflow==2.1.0

     |████████████████████████████████| 421.8MB 35kB/s 
     |████████████████████████████████| 450kB 39.4MB/s 
     |████████████████████████████████| 3.8MB 32.3MB/s 
     |████████████████████████████████| 81kB 6.5MB/s 
ERROR: tensorboard 2.1.0 has requirement grpcio>=1.24.3, but you'll have grpcio 1.15.0 which is incompatible.
ERROR: google-colab 1.0.0 has requirement google-auth~=1.4.0, but you'll have google-auth 1.10.1 which is incompatible.
  Found existing installation: tensorflow-estimator 1.15.1
    Uninstalling tensorflow-estimator-1.15.1:
      Successfully uninstalled tensorflow-estimator-1.15.1
  Found existing installation: google-auth 1.4.2
    Uninstalling google-auth-1.4.2:
      Successfully uninstalled google-auth-1.4.2
  Found existing installation: tensorboard 1.15.0
    Uninstalling tensorboard-1.15.0:
      Successfully uninstalled tensorboard-1.15.0


In [0]:
#Now we have to restart Runtime
#Click above

In [1]:
import numpy as np
import tensorflow as tf
print(tf.__version__)

2.1.0


In [0]:
P = np.array([[0.5,0,0.5,],
             [0,0.75,0.25],
             [0.5,0.5,0]])

In [3]:
P

array([[0.5 , 0.  , 0.5 ],
       [0.  , 0.75, 0.25],
       [0.5 , 0.5 , 0.  ]])

In [0]:
pi0 = np.array([1,0,0], dtype=float)

In [5]:
pi0

array([1., 0., 0.])

In [6]:
#P to the 3rd power
P3 = np.dot(np.dot(P,P),P)
P3

array([[0.375   , 0.3125  , 0.3125  ],
       [0.15625 , 0.609375, 0.234375],
       [0.3125  , 0.46875 , 0.21875 ]])

In [7]:
np.sum(P3,axis=1)

array([1., 1., 1.])

In [0]:
pi3 = np.dot(pi0,P3)

In [9]:
pi3

array([0.375 , 0.3125, 0.3125])

In [10]:
np.sum(pi3)

1.0

In [11]:
pi1 = np.dot(pi0,P)
pi1

array([0.5, 0. , 0.5])

In [12]:
pi2 = np.dot(pi1,P)
pi2

array([0.5 , 0.25, 0.25])

In [13]:
pi33 = np.dot(pi2,P)
pi33

array([0.375 , 0.3125, 0.3125])

In [15]:
tfP = tf.constant([[0.5,0,0.5,],
                   [0,0.75,0.25],
                   [0.5,0.5,0]])
tf.print(tfP)
#with tf.Session() as sess:  print(tfP.eval()) 

[[0.5 0 0.5]
 [0 0.75 0.25]
 [0.5 0.5 0]]


In [16]:
tfpi0 = tf.constant([1,0,0], dtype=float)
tf.print(tfpi0)

[1 0 0]


In [17]:
tfpi1 = tf.linalg.matvec(tfP,tfpi0)
tf.print(tfpi1)

[0.5 0 0.5]


In [18]:
tfP3 = tf.matmul(tfP,tf.matmul(tfP,tfP))
tf.print(tfP3)

[[0.375 0.3125 0.3125]
 [0.15625 0.609375 0.234375]
 [0.3125 0.46875 0.21875]]


In [19]:
P3

array([[0.375   , 0.3125  , 0.3125  ],
       [0.15625 , 0.609375, 0.234375],
       [0.3125  , 0.46875 , 0.21875 ]])

In [20]:
tfpi3 = tf.matmul(tf.expand_dims(tfpi0,0),tfP3)
tf.print(tfpi3)

[[0.375 0.3125 0.3125]]


In [21]:
pi3

array([0.375 , 0.3125, 0.3125])

In [0]:
tfpi0_0 = tf.constant([0.25,0.5,0.25])

In [23]:
tfpi1_1 = tf.matmul(tf.expand_dims(tfpi0_0,0),tfP)
tf.print(tfpi1_1)

[[0.25 0.5 0.25]]
